### ISSUE TITLE
auto-expand alias after <Enter> key is pressed

### ISSUE THREAD

**Issue by jetm** [MenkeTechnologies/zsh-expand#4]
Thank you for this useful plugin.

There is something I am missing in `zsh-expand` that `zsh-abbrev-alias` does. When I type the alias and press the <Enter> key, `zsh-expand` doesn't expand the alias, and in the history, the alias is saved instead of the whole command. Could an option be added to make expand the alias after a key is pressed?

**Comment by MenkeTechnologies** [comment]
would this be in the command position with regular aliases only or globally?

it is easy to do b/c zsh has a hook for it... zshaddhistory_functions

**Comment by MenkeTechnologies** [comment]
in your config before sourcing plugin add

```sh
export ZPWR_EXPAND_TO_HISTORY=true
```

after running command with unexpanded alias, the expanded alias or aliases will be in history up 2 lines with unexpanded up 1 line.   After running another command the unexpanded line will be gone.  this is the way zsh addhistory hook functions work when returning 1.

This uses exact same rules as expand on spacebar so `sudo gco` will expand to sudo git checkout if you have `alias gco=git checkout` etc...

**Comment by MenkeTechnologies** [comment]
if you use zpwr, I have the aliases expanding before command line is executed so up 1 line has expanded form already

**Comment by jetm** [comment]
It works. Thank you!
