### ISSUE TITLE
Ignore list

### ISSUE THREAD

**Issue by kevintraver** [MenkeTechnologies/zsh-expand#6]
Oh My Zsh Globalias has a setting `GLOBALIAS_FILTER_VALUES` which ignores expanding certain values.

Is there a way to do this? 

If not it would be a helpful feature to have.

**Comment by MenkeTechnologies** [comment]
yeah, I already have setup several blacklists like you are mentioning.  Looks like a blacklist in command position.  I have blacklists setup for many positions including command position.  I will add an environment variable to allow a user blacklist for global and regular aliases.

**Comment by MenkeTechnologies** [comment]
ZPWR_EXPAND_BLACKLIST should be set as an array of regular or global aliases to blacklist

**Comment by kevintraver** [comment]
Awesome, Thank you!
